### ISSUE TITLE
User stories for "Hello world + Compile / Code completion" prototype

### ISSUE THREAD

**Issue by CSchoel** [MopeSWTP-SS21/MopeSWTP#14]
The goal of our first sprint will be to build a "hello world" prototype that establishes the communication pipeline from an external LSP command to a reaction of the OMC and back to an answer through the LSP channel.

I have tried to write up the features that M. Wächtershäuser and I agreed upon as user stories in hope of facilitating our agile workflow. :smile: 

- [x] As developer I can start the Mo|E server process from the console.
- [x] As developer I can use some console application or GUI to send a command per LSP to the Mo|E server process and receive an answer.
- [x] As developer I can trigger the Mo|E server process via console or LSP command to send a command per ZeroMQ to the OpenModelica compiler (OMC) and see the answer of the OMC in the console.
    - In order to do this, a minimalist console application using LSP4J should be developed.
- [x] As developer I can trigger the Mo|E server process via an LSP command to do at least ONE of the following, so I can already use the prototype productively beyond a simple "Hello world" example.
  - Load a model with the `loadModel()` command of the OpenModelica Scripting API receiving syntax errors with line numbers (as detailed in #19)
  - Receive simple code completion hints for fully qualified class names (i.e. without considering imports, as detailed in #21)
- [x] As developer I can trigger a build in GitHub actions that compiles the current version of the Mo|E server via a commit to the main branch.
- [x] As user I can follow a step-by-step description in the project README to compile and run the server prototype on my machine.

Note that the last issue was not discussed in our meeting today, but I added it afterwards since I want to ensure that the project has at least a minimal user documentation.

**Comment by CSchoel** [comment]
FYI: I have changed the name of the Label from "PO Request" to "Epic" since, as one of you already said, this really seems to be the correct name within the agile terminology.

**Comment by CSchoel** [comment]
As discussed with @manuEbg , I added a new task to the list and changed the title, since I think that after four weeks of active development, we should have more than a simple "Hello World"-Prototype.

**Comment by CSchoel** [comment]
Also a quick note: This Epic needs at least one more sub-issue for the development of the GH Actions workflow.

**Comment by CSchoel** [comment]
I added another note to document that we agreed that the prototype should provide a minimalist console application to send LSP commands vial LSP4J.

**Comment by manuEbg** [comment]
In the latest version of LSPConsole it is possible to send an lsp executeCommand to TestServer who responds with the Version of connected omccompiler. 
I wont check any checkboxes, since code is bad, not yet useful and full of questions...

**Comment by manuEbg** [comment]
I figured out, that in the OMShell I can load the StandardLibrary via commend  `loadModel(Modelica)`
however to load my self-written Model i have to call `loadFile(".../package.mo")`
 
I am wondering if the only purpose of  loadModel is to load the standard Library like it reads here ? 
https://build.openmodelica.org/Documentation/OpenModelica.Scripting.loadModel.html

Or if i am doing something wrong and I should be able to load my self-written Models via loadModel?
Because this is what i think when reading the Issue description.

Maybe @CSchoel can clarify? 

Edit:
loadModel seems to be able to load "published" Libraries. for example i can execute `loadModel(BioChem)`

**Comment by CSchoel** [comment]
Have a look at the [example code](https://homepages.thm.de/~cslz90/kurse/swtp21/example_most.mos) I gave you at one of our first meetings. This shows how `loadModel()` has to be used with custom models. Basically, the model file must be available from the Modelica path. The OpenModelica Scripting API documentation is a little misleading in this regard. `loadModel()` is in fact used for all kinds of models, not just the MSL.

**Comment by manuEbg** [comment]
> 
> 
> Have a look at the [example code](https://homepages.thm.de/~cslz90/kurse/swtp21/example_most.mos) I gave you at one of our first meetings. This shows how `loadModel()` has to be used with custom models. Basically, the model file must be available from the Modelica path. The OpenModelica Scripting API documentation is a little misleading in this regard. `loadModel()` is in fact used for all kinds of models, not just the MSL.

Thanks! This was great help:)
