### ISSUE TITLE
As Modelica programmer, I can load models of arbitrary sizes, structure, and complexity with Mo|E, so I can immediately start working on my projects without worrying about compatibility issues

### ISSUE THREAD

**Issue by CSchoel** [MopeSWTP-SS21/MopeSWTP#20]
- [ ] Modelica classes can be defined like Java classes with a one-to-one relation between classes and files, but it is also possible to only have one file per package, which contains all classes within that package (and its sub-packages). Both definition styles can be mixed aribtrarily. Mo|E should therefore support both styles and never assume that there has to be a one-to-one relation between classes and files.
- [ ] Modelica has a very rich feature set. For example, it allows to define arbitrary functions using C syntax including system calls or calls to other C libraries, has a vector syntax for defining connectors of arbitrary size, or includes a special keyword `stream` for describing flows of matter. These special features will not occur in most models, but Mo|E should nevertheless be able to handle them. This will be guaranteed for all Operations that only involve the OMC, because OpenModelica implements all relevant features. However, if a custom Modelica parser is used somewhere within Mo|E, special care should be taken that it also correctly parses more "exotic" models.
- [ ] As a minimum, development of the following models should be possible in Mo|E:
    - [x] [https://github.com/CSchoel/hh-modelica](https://github.com/CSchoel/hh-modelica)
    - [x] [https://github.com/CSchoel/shm-conduction](https://github.com/CSchoel/shm-conduction)
    - [x] [https://github.com/CSchoel/shm](https://github.com/CSchoel/shm)
    - [x] [https://github.com/CSchoel/inamo](https://github.com/CSchoel/inamo)
