### ISSUE TITLE
As Modelica programmer, I can request an HTML rendering of the Documentation of a Modelica class via LSP, so I can check my own documentation for errors and explore unknown library classes

### ISSUE THREAD

**Issue by CSchoel** [MopeSWTP-SS21/MopeSWTP#22]
- [ ] This call should have two distinct modes for returned data:
  - [ ] It can be a standalone HTML document containing a doctype definition, encoding, and everything. In this case, a minimal but nice looking CSS stylesheet should also be provided. This version is intended for documentation export to a file and for display in a browser.
  - [ ] The other version should contain no styling, no header, and no surrounding `<html>` tag, so that it can be easily inserted into a larger HTML document or styled, for example, by a text editor that displays the HTML snippet in a tooltip.
- [ ] Links to image files and other Modelica classes should be translated to working HTML links as far as possible.
- [ ] HTML documentation can either be requested for a file (i.e. for the toplevel class in that file) or for a fully qualified class name.
- [ ] If a class does not have a `annotation(documentation(info="..."))` string, the returned string should contain a text message stating that there is no documentation for this class.
